### ISSUE TITLE
[advice] Add url https://termux-user-repository.github.io/pypi/

### ISSUE THREAD

**Issue by Freed-Wu** [termux-user-repository/pypi#1]
Can this project (and https://github.com/termux-user-repository/pypi-index-tur) add url https://termux-user-repository.github.io/pypi/ to README or Website of repository details? It can make user find the website. TIA!

**Comment by licy183** [comment]
https://github.com/termux-user-repository/tur/commit/ea3759be5405f4ae858caeaa88585c5f2f64bfca

**Comment by Freed-Wu** [comment]
How about here:

![Screenshot from 2023-05-24 05-46-38](https://github.com/termux-user-repository/pypi/assets/32936898/6414bd32-d838-4b1c-b903-6f9cd4d082f8)

**Comment by licy183** [comment]
> How about here:
> 
> ![Screenshot from 2023-05-24 05-46-38](https://user-images.githubusercontent.com/32936898/240426579-6414bd32-d838-4b1c-b903-6f9cd4d082f8.png) ![Screenshot from 2023-05-24 05-52-35](https://user-images.githubusercontent.com/32936898/240427566-2657fb2d-03f7-49e7-86b2-3e15684ac9d8.png)

Added. Thanks for your suggestion.
